
name: build .NET

on:
  push:
    branches:
      - 'develop'
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout the repo
    - uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: execute tests
      run: dotnet test --no-build --verbosity normal
